[TEMP]:Revert some  lmk configs
Due to duplicate props defined in vendor/lineage/config/common.mk
error: found duplicate sysprop assignments:
ro.lmk.upgrade_pressure=100
ro.lmk.upgrade_pressure=40
error: found duplicate sysprop assignments:
ro.lmk.medium=800
ro.lmk.medium=701
error: found duplicate sysprop assignments:
ro.lmk.critical_upgrade=false
ro.lmk.critical_upgrade=true
error: found duplicate sysprop assignments:
ro.lmk.downgrade_pressure=100
ro.lmk.downgrade_pressure=60